name: btrack_app
description: BTRACK - Bus Tracking System (Community)

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  qr_code_scanner: ^1.0.1
  fluttertoast: ^8.2.2
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
